# Configuration Constants for RL Robot Environment

RLConfig:
  # --- Robot Configuration ---
  PORT: '/dev/ttyACM0'
  CONTROL_MODE: "position"
  JOINT_LIMITS:
    # # Original Joint Limits
    - [-180, 180] # Joint 0 (Base Rotation)
    - [-88, 88]   # Joint 1 (Shoulder)
    - [-145, 145] # Joint 2 (Elbow)
    - [-180, 180] # Joint 3 (Wrist Yaw)
    - [-180, 180] # Joint 4 (Wrist Pitch)
    - [-180, 180] # Joint 5 (Gripper Rotation)
    # - [-30, 90]       # Joint 0 (Base Rotation)
    # - [17.3, 17.3]    # Joint 1 (Shoulder)
    # - [128.9, 128.9]  # Joint 2 (Elbow)
    # - [60.2, 60.2]    # Joint 3 (Wrist Yaw)
    # - [0, 0]          # Joint 4 (Wrist Pitch)
    # - [0, 0]          # Joint 5 (Gripper Rotation)
    # the unlimited range:
    # - [-180, 180] # Joint 0 (Base Rotation)
    # - [-180, 180]   # Joint 1 (Shoulder)
    # - [-180, 180] # Joint 2 (Elbow)
    # - [-180, 180] # Joint 3 (Wrist Yaw)
    # - [-180, 180] # Joint 4 (Wrist Pitch)
    # - [-180, 180] # Joint 5 (Gripper Rotation)
  # Original Combined Joint 2-3 Limit
  COMBINED_JOINT_2_3_LIMIT: -1  # Set to <=0 to disable (default: 105)

  # --- OptiTrack Configuration ---
  NATNET_SERVER_IP: '192.168.1.2'
  NATNET_CONNECT_TIMEOUT: 5
  NATNET_RIGID_BODY_IDS:
    end_effector: 15
    table: 14

  TARGET_MIN_X_CORRECTED: 0.15
  TARGET_MAX_X_CORRECTED: 0.65
  TARGET_MIN_Y_CORRECTED: -0.2
  TARGET_MAX_Y_CORRECTED: 0.2
  TARGET_MIN_Z_CORRECTED: 0.4
  TARGET_MAX_Z_CORRECTED: 0.8

  TARGET_MIN_X: -0.3
  TARGET_MAX_X: 0.3
  TARGET_MIN_Y: -0.3
  TARGET_MAX_Y: 0.3
  TARGET_MIN_Z: 0.0
  TARGET_MAX_Z: 0.85

  TARGET_CYLINDER_RADIUS: 0.5
  TARGET_CYLINDER_HEIGHT_MAX: 0.8
  TARGET_CYLINDER_HEIGHT_MIN: 0.45
  TARGET_CYLINDER_MINIMUM_DISTANCE: 0.35

  FIXED_TARGET_POSITION: [0.226, 0.0, 0.2]  # ENV - Used when target_pos_sampling_method is "fixed"

  # --- Target Sampling Method ---
  KINEMATIC_SAMPLING_POINTS: 10000

  # --- Environment Parameters ---
  # ACTION_RANGE_DEG: 5.0
  ACTION_EXECUTION_TIME_SEC: 0.05
  RENDER_FPS: 10

  RL_ENV_RESET_SEC: 3

  # --- Main Script/Stress Test Configuration ---
  WATCHDOG_INTERVAL: 0.01
  MARKER_RADII:
    1: 0.025
    2: 0.025
    3: 0.025
    4: 0.025
    5: 0.025
    6: 0.025

  # --- Stress Test Configuration ---
  STRESS_TEST_ITERS: 1000
  STRESS_TEST_INTERVAL: 0.05

  # --- RL Training Configuration ---
  RL_CONTROL_INTERVAL: 0.05

TrainConfig:
  # Experiment
  project: "LynxReach"
  group: "Sim"
  name: "mujoco"
  device: "cuda:0" # Default, will be overridden by platform.node()
  seed: 0
  base_log_dir: ".results/" # Default, will be overridden by platform.node()
  algo: "SAC"
  model_save_freq: 500000
  total_timesteps: 5000000
  num_envs: 1
  render_mode: "human"  # human, rgb_array
  action_mode: "rel_abs"  # ENV
  real_time_speed: false  # ENV
  collision_detection: true

  # exp callback:
  eval_episode_freq: 100
  epi_rest_freq: null  # null for sim
  n_eval_episodes: 1

  # SAC/PPO common
  learning_rate: 0.0003
  batch_size: 256
  gamma: 0.99
  stats_window_size: 1

  # SAC specific
  tau: 0.005
  train_freq_str: "1,episode"
  gradient_steps: 200
  learning_starts: 10000
  sac_net_arch_pi: [512, 256, 128]
  sac_net_arch_qf: [512, 256, 128]

  # PPO specific
  ppo_n_steps: 2048
  ppo_n_epochs: 10
  ppo_gae_lambda: 0.95
  ppo_ent_coef: 0.001
  ppo_clip_range: 0.2
  ppo_vf_coef: 1.0
  ppo_net_arch_pi: [512, 256, 128]
  ppo_net_arch_vf: [512, 256, 128]

  # Enviornment specific
  time_step: 0.016666666666666666 # 1.0/60.0  # ENV
  control_frequency: 5  # ENV
  v_start_scale: 1.0  # ENV
  action_range_deg: 10.0  # ENV
  reset_random_scale: 0.3 # ENV - Scale for random reset range
  clip_action_scale: 1.0 # ENV - Scale for clipping action to avoid extreme commands (set to 1.0 to disable clipping)
  target_pos_sampling_method: "fixed"  # ENV - "sphere", "cylinder", "table", "fixed", or "kinematic_sampling"
  kinematic_sampling_points: 10000
  max_speed: 2000.0  # ENV
  motor_acceleration: 100.0  # ENV
  max_steps_per_episode: 50  # ENV
  fixed_target_orientation: [0.0, 0.70710678118, 0.0, 0.70710678118] # np.sqrt(2)/2  # ENV
  real_lynx: false  # ENV
  reward_type: "pos"  # ENV
  goal_tolerance_m: 0.05  # ENV
  # reward_scaling_factor: 10.0
  sphere_target_range: 0.5  # ENV
  distance_threshold: 0.03  # ENV

  model_dir: ".results/models" # Default, will be overridden by platform.node()
  load_model_path: null
  load_replay_buffer_path: null

  # Offline RL specific:
  vis_target_sphere: true
  use_camera: false
  collect_imu: false
  real_time_latency: 0.08  # ENV - Compensate for real-world latency in seconds
  use_random_action_for_data_collection: true
  static_viewer: false  # ENV - If true, the viewer will use a fixed camera view defined in the model. If false, it will use a free camera that can be controlled by the user.

TestConfig:
  # model_path: "/home/zuxinrui/LynxRobotics/.results/sim_sac/lynxsim-models_2025-11-05_12-28-03/mujoco-SAC-lynxsim-models_2025-11-05_12-28-03_best_ee_pos_model_3560000.zip"
  model_path: "/home/zuxinrui/LynxRobotics/.results/sim_push_sac/lynxpush-models_2026-03-11_01-12-54/mujoco-push-SAC-lynxpush-models_2026-03-11_01-12-54_best_ee_pos_model_1280000_dist_0.0951.zip"

OfflineTrainConfig:
  # data_collection:
  total_timesteps: 1000000
  batch_size: 256
  dataset_path: "/home/zuxinrui/LynxRobotics/.results/sim_reach_ompl_collection/ompl_collection_2026-03-12_12-34-05/replay_buffer.pkl"

MorphConfig:
  robot_description_dict:
    # =============== robot morphology params ===============:
    num_joints: 6  # 1-6
    ## tube positions:
    genotype_tube: [1, 1, 0, 1, 0]  # 0: straight_tube, 1: next_joint_pose defalult: [0,1,0,1,0]
    ## tube 1: real choices: pos [0, 0.05, 0.2] theta 30.0; pos [0, 0.1, 0.2] theta 45.0; pos [0, 0.1, 0.25] theta 45.0
    l1_end_point_pos: [0.0, 0.0, 0.2805]  # y range: [-0.2, 0.2] z range: [0.1, 0.36]. default: [0.0, 0.0, 0.4125]  # large joint offset: 7.5 cm; small joint offset: 5.0 cm
    l1_end_point_theta: 0.0  # y-z plane, angle range: [-180, 180]
    ## tube 2:
    l2_end_point_pos: [0.0, 0.0, 0.2805]  # default: [0.0, 0.0, 0.41259]
    l2_end_point_theta: 0.0  # y-z plane, angle range: [-180, 180]
    ## tube 3:
    l3_end_point_pos: [0.0, 0.0, 0.2]  # default: [0.0, 0.0, 0.41259]
    l3_end_point_theta: 0.0  # y-z plane, angle range: [-180, 180]
    ## tube 4:
    l4_end_point_pos: [0.0, 0.0, 0.2]  # default: [0.0, 0.0, 0.41259]
    l4_end_point_theta: 0.0  # y-z plane, angle range: [-180, 180]
    ## tube 5:
    l5_end_point_pos: [0.0, 0.0, 0.2]  # default: [0.0, 0.0, 0.41259]
    l5_end_point_theta: 0.0  # y-z plane, angle range: [-180, 180]
    ## joint types:
    genotype_joints: 0  # range: {0,1,2,3,4,5}. default: 1
    ## joint fixed-side angles:
    rotation_angles: [180, 0, 0, -180, 0, 0]  # default: [180, 0, 0, -180, 0, 0]
    # =============== other static params ===============:
    clamp_length: 0.0359  # version: models/clamp_1216.stl
    dual_point_distance: 0.07
    num_segments: 100
    tube_radiuses: [0.0396, 0.0396, 0.0396, 0.0396, 0.0396]
    tube_colors: [
        [0.085, 0.394, 0.350, 1],
        [0.085, 0.394, 0.350, 1],
        [0.085, 0.394, 0.350, 1],
        [0.085, 0.394, 0.350, 1],
        [0.085, 0.394, 0.350, 1],
        ]  # black: [0.1, 0.1, 0.1, 1.0]  gray blue: [0.68, 0.76, 0.82, 1.0]  orange: [1., 0.745, 0.298, 1] dark green: [0.085, 0.394, 0.350, 1]
    clamp_stl: "models/clamp_0226.stl"
    task: "reach" # default: "reach". range: {"reach", "ball in cup", "push"}
    collision_alpha: 0.0  # default: 0.5, range: [0,1], alpha value for tube collision visualization (0: invisible, 1: fully opaque)

checkpoint_groups:
  - ".results/sim_sac/lynxsim-offline"

DomainRand:
  enable: false

  # ---- Control/Actuation DR <action> ----
  action_noise:
    enable: true
    std: 0.005          # rad, additive Gaussian on action (before clip)

  action_delay:
    enable: false
    min_steps: 0       # delay in controller steps (NOT sim steps)
    max_steps: 3

  action_bias:
    enable: false
    std: 0.005   # rad, per-dimension bias sampled per episode

  # ---- <dynamics> ----

  dynamics_limits:
    enable: true
    vmax_scale:
      low: 0.8
      high: 1.2
    amax_scale:
      low: 0.8
      high: 1.2
    kp_scale:
      low: 0.8
      high: 1.2
    kd_scale:
      low: 0.8
      high: 1.2

  # ---- <observation> ----
  obs_noise:
    enable: true
    ee_pos_std: 0.002  # meters (2mm)
    qpos_std: 0.002    # rad

  obs_bias:
    enable: false
    ee_pos_std: 0.005  # meters, per episode constant offset

  # ---- <timing> ----
  timing:
    enable: true
    latency_sec:
      low: 0.02
      high: 0.09
    control_frequency_hz:
      low: 2
      high: 10

  # Seed control (optional)
  deterministic: false
  seed: 0



